#!/usr/bin/env bash
# install and configure haproxy

# Install HAproxy for Ubuntu 20.04
sudo apt-get -y update
sudo apt-get -y install haproxy

# Create backup of the HAProxy configuration file
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_frontend
        bind *:80
        mode http
        default_backend http_backend
backend http_backend
        balance roundrobin
        server web-01 54.237.56.74:80 check
        server web-02 54.158.182.112:80 check
EOT

# Enable HAproxy to be started by an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
