#!/usr/bin/env bash
# Installing HAproxy on server and serving a basic html
#  and adding a permanent redirection to a youtube video
#  as well as a custom 404 error page and header

# Installation of HAproxy
sudo apt-get update
sudo apt-get -y install haproxy
# Creating backup of the HAProxy configuration file
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
# Configuring HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_frontend
        bind *:80
        mode http
        default_backend http_backend
backend http_backend
        balance roundrobin
        server web-01 54.237.56.74:80 check
        server web-02 54.158.182.112:80 check
EOT
# Enabling HAproxy to be started by an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# To refresh the caches and pick up new changes
sudo service haproxy restart
