#!/usr/bin/env bash
# Displays numbers from 1 to 20 and displays
#+ 4 and "bad luck from China" @ 4th loop iteration
#+ 9 and "bad luck from Japan" @ 9th loop iteration
#+ 17 and "bad luck from Italy" @ 17th loop iteration

i=1

while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	
	#echo "$i"
	i=$((i + 1))
done
